Service Worker Import Fix
I encountered this a bit ago too, and also was too confused how to fix this, or rather probably too stubborn. This works at least, I really did like the named imports though. I don't want to change the module resolution though, since it might mess up other things unintentionally.

```
> smart-text-editor@5.8.0 build
> tsc && tsc --project ./src/service-worker/tsconfig.json && vite build

src/service-worker/service-worker.ts(1,10): error TS1544: Named imports from a JSON file into an ECMAScript module are not allowed when 'module' is set to 'NodeNext'.
src/service-worker/service-worker.ts(1,36): error TS1543: Importing a JSON file into an ECMAScript module requires a 'type: "json"' import attribute when 'module' is set to 'NodeNext'.
```